export class trfollow {
    followId: number;
    debtCollectionNumber: string;
    followType: string;
    followDate: string;
    contactName: string;
    followDetail: string;
    amount: number;
    amountNote: string;
    status: string;
    result: string;
    nextFollowNote: string;
    nextFollowDate: string;
    nextFollowStatus: string;
    phoneNumber: string;
    paymentType: string;
    numberOfMonth: number;
    payPerMonth: number;
    active: string;
    remark: string;
    createdBy: string;
    createDate: Date;
    updatedBy: string;
    updateDate: Date;
};